/*
 * Copyright (C) 2019 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import androidx.build.AndroidXRootPlugin
import androidx.build.SdkHelperKt

buildscript {
    SdkHelperKt.setSupportRootFolder(project, project.projectDir)
    SdkHelperKt.writeSdkPathToLocalPropertiesFile(project)

    apply from: "${rootDir}/build_properties.gradle"
    def buildProperties = extensions.findByName("build_properties")

    repositories {
        def customUrl = buildProperties.get("custom_maven_url")
        if (customUrl != null && customUrl != "") {
            maven {
                url = customUrl
            }
        }
        maven {
            url = "https://artifact.bytedance.com/repository/releases"
        }
    }

    // Needed for atomicfu plugin
    apply(from: "buildSrc/repos.gradle")
    repos.addMavenRepositories(repositories)
    dependencies {
        classpath(libs.atomicFuPluginz)
        // This should be removed once https://github.com/Kotlin/kotlinx-atomicfu/issues/399 is fixed
        classpath("org.jetbrains.kotlin:atomicfu:${libs.versions.kotlin.get()}")
    }
}

apply from: "buildSrc/dependencies.gradle"

apply plugin: AndroidXRootPlugin

// workaround for https://github.com/gradle/gradle/issues/24822
if (project.hasProperty("androidx.update.signatures")) {
    apply plugin: "java-library"
    apply from: "buildSrc/shared-dependencies.gradle"
}

def buildProperties = extensions.findByName("build_properties")

allprojects {
    this.tasks.configureEach {
        if (it.name == "kotlinStoreYarnLock") it.enabled = false
    }
}

allprojects {
    repositories {
        def customUrl = buildProperties.get("custom_maven_url")
        if (customUrl != null && customUrl != "") {
            maven {
                url = customUrl
            }
        }
        maven {
            url = "https://artifact.bytedance.com/repository/releases"
        }
    }

    configurations.all {
        resolutionStrategy.eachDependency { DependencyResolveDetails details ->
            if (details.requested.name == "kotlinx-coroutines-test" &&
                    details.requested.group == "org.jetbrains.kotlinx") {
                details.useVersion "1.8.1-bytekmp.2"
            }
            else if (details.requested.name == "kotlinx-coroutines-core" &&
                    details.requested.group == "org.jetbrains.kotlinx") {
                details.useVersion "1.8.1-bytekmp.2"
            }
            else if (details.requested.name == "kotlin-test-junit" &&
                    details.requested.group == "org.jetbrains.kotlin") {
                details.useVersion "1.9.22"
            }
            else if (details.requested.name == "kotlinx-coroutines-android" &&
                    details.requested.group == "org.jetbrains.kotlinx") {
                details.useVersion "1.8.1"
            }
            else if(details.requested.name == "atomicfu" &&
                    details.requested.group == "org.jetbrains.kotlinx") {
                details.useVersion("0.25.0-bytekmp.4")
            }
            else if(details.requested.name == "skiko-js-wasm-runtime" &&
                    details.requested.group == "org.jetbrains.skiko") {
                details.useVersion("0.8.4")
            }
            else if(details.requested.name == "skiko-awt-runtime-macos-arm64" &&
                    details.requested.group == "org.jetbrains.skiko") {
                details.useVersion("0.8.4")
            }
            else if(details.requested.name == "paging-common" &&
                    details.requested.group == "androidx.paging") {
                details.useVersion("2.1.1")
            }
        }
    }
}